//
//  UIColor+FIAdditions.swift
//
//  Generated by Zeplin on 4/5/16.
//  Copyright (c) 2016 __MyCompanyName__. All rights reserved. 
//

import UIKit

extension UIColor {
	class func fiGreyishBrownColor() -> UIColor {
		return UIColor(white: 84.0 / 255.0, alpha: 1.0)
	}

	class func fiDuckEggBlueColor() -> UIColor {
		return UIColor(red: 226.0 / 255.0, green: 248.0 / 255.0, blue: 246.0 / 255.0, alpha: 1.0)
	}

	class func fiTurquoiseColor() -> UIColor {
		return UIColor(red: 3.0 / 255.0, green: 188.0 / 255.0, blue: 165.0 / 255.0, alpha: 1.0)
	}

	class func fiGreenblueColor() -> UIColor {
		return UIColor(red: 1.0 / 255.0, green: 178.0 / 255.0, blue: 158.0 / 255.0, alpha: 1.0)
	}

	class func fiLightSageColor() -> UIColor {
		return UIColor(red: 226.0 / 255.0, green: 248.0 / 255.0, blue: 229.0 / 255.0, alpha: 1.0)
	}

	class func fiCharcoalGreyColor() -> UIColor {
		return UIColor(red: 53.0 / 255.0, green: 53.0 / 255.0, blue: 54.0 / 255.0, alpha: 1.0)
	}

	class func fiDarkishPinkColor() -> UIColor {
		return UIColor(red: 213.0 / 255.0, green: 74.0 / 255.0, blue: 113.0 / 255.0, alpha: 1.0)
	}
}
