//
//  TFCard.generated.swift
//
//  This code was generated by AlecrimCoreData code generator tool.
//
//  Changes to this file may cause incorrect behavior and will be lost if
//  the code is regenerated.
//

import Foundation
import CoreData

import AlecrimCoreData

// MARK: - TFCard properties

extension TFCard {

    @NSManaged public var cardholder: NSString?
    @NSManaged public var expirationDate: NSDate?
    @NSManaged public var identifier: NSString?
    @NSManaged public var name: NSString?
    @NSManaged public var number: NSNumber?

    @NSManaged public var transactions: NSSet

}

// MARK: - TFCard KVC compliant to-many accessors and helpers

extension TFCard {

    @NSManaged private func addTransactionsObject(object: TFTransaction)
    @NSManaged private func removeTransactionsObject(object: TFTransaction)
    @NSManaged public func addTransactions(transactions: NSSet)
    @NSManaged public func removeTransactions(transactions: NSSet)

    public func addTransaction(transaction: TFTransaction) { self.addTransactionsObject(transaction) }
    public func removeTransaction(transaction: TFTransaction) { self.removeTransactionsObject(transaction) }

}

// MARK: - TFCard query attributes

extension TFCard {

    public static let cardholder = AlecrimCoreData.NullableAttribute<NSString>("cardholder")
    public static let expirationDate = AlecrimCoreData.NullableAttribute<NSDate>("expirationDate")
    public static let identifier = AlecrimCoreData.NullableAttribute<NSString>("identifier")
    public static let name = AlecrimCoreData.NullableAttribute<NSString>("name")
    public static let number = AlecrimCoreData.NullableAttribute<NSNumber>("number")

    public static let transactions = AlecrimCoreData.Attribute<NSSet>("transactions")

}

// MARK: - AttributeType extensions

extension AlecrimCoreData.AttributeType where Self.ValueType: TFCard {

    public var cardholder: AlecrimCoreData.NullableAttribute<NSString> { return AlecrimCoreData.NullableAttribute<NSString>("cardholder", self) }
    public var expirationDate: AlecrimCoreData.NullableAttribute<NSDate> { return AlecrimCoreData.NullableAttribute<NSDate>("expirationDate", self) }
    public var identifier: AlecrimCoreData.NullableAttribute<NSString> { return AlecrimCoreData.NullableAttribute<NSString>("identifier", self) }
    public var name: AlecrimCoreData.NullableAttribute<NSString> { return AlecrimCoreData.NullableAttribute<NSString>("name", self) }
    public var number: AlecrimCoreData.NullableAttribute<NSNumber> { return AlecrimCoreData.NullableAttribute<NSNumber>("number", self) }

    public var transactions: AlecrimCoreData.Attribute<NSSet> { return AlecrimCoreData.Attribute<NSSet>("transactions", self) }

}

// MARK: - DataContext extensions

extension DataContext {

    public var tfcards: AlecrimCoreData.Table<TFCard> { return AlecrimCoreData.Table<TFCard>(dataContext: self) }

}

