//
//  TFCard.generated.swift
//
//  This code was generated by AlecrimCoreData code generator tool.
//
//  Changes to this file may cause incorrect behavior and will be lost if
//  the code is regenerated.
//

import Foundation
import CoreData

import AlecrimCoreData

// MARK: - TFCard properties

extension TFCard {

    @NSManaged var cardholder: NSString?
    @NSManaged var expirationDate: NSDate?
    @NSManaged var identifier: NSString?
    @NSManaged var name: NSString?
    @NSManaged var number: NSNumber?

    @NSManaged var transactions: NSSet

}

// MARK: - TFCard KVC compliant to-many accessors and helpers

extension TFCard {

    @NSManaged private func addTransactionsObject(object: TFTransaction)
    @NSManaged private func removeTransactionsObject(object: TFTransaction)
    @NSManaged func addTransactions(transactions: NSSet)
    @NSManaged func removeTransactions(transactions: NSSet)

    func addTransaction(transaction: TFTransaction) { self.addTransactionsObject(transaction) }
    func removeTransaction(transaction: TFTransaction) { self.removeTransactionsObject(transaction) }

}

// MARK: - TFCard query attributes

extension TFCard {

    static let cardholder = AlecrimCoreData.NullableAttribute<NSString>("cardholder")
    static let expirationDate = AlecrimCoreData.NullableAttribute<NSDate>("expirationDate")
    static let identifier = AlecrimCoreData.NullableAttribute<NSString>("identifier")
    static let name = AlecrimCoreData.NullableAttribute<NSString>("name")
    static let number = AlecrimCoreData.NullableAttribute<NSNumber>("number")

    static let transactions = AlecrimCoreData.Attribute<NSSet>("transactions")

}

// MARK: - AttributeType extensions

extension AlecrimCoreData.AttributeType where Self.ValueType: TFCard {

    var cardholder: AlecrimCoreData.NullableAttribute<NSString> { return AlecrimCoreData.NullableAttribute<NSString>("cardholder", self) }
    var expirationDate: AlecrimCoreData.NullableAttribute<NSDate> { return AlecrimCoreData.NullableAttribute<NSDate>("expirationDate", self) }
    var identifier: AlecrimCoreData.NullableAttribute<NSString> { return AlecrimCoreData.NullableAttribute<NSString>("identifier", self) }
    var name: AlecrimCoreData.NullableAttribute<NSString> { return AlecrimCoreData.NullableAttribute<NSString>("name", self) }
    var number: AlecrimCoreData.NullableAttribute<NSNumber> { return AlecrimCoreData.NullableAttribute<NSNumber>("number", self) }

    var transactions: AlecrimCoreData.Attribute<NSSet> { return AlecrimCoreData.Attribute<NSSet>("transactions", self) }

}

// MARK: - DataContext extensions

extension DataContext {

    var tfcards: AlecrimCoreData.Table<TFCard> { return AlecrimCoreData.Table<TFCard>(dataContext: self) }

}

