//
//  TFRecipient.generated.swift
//
//  This code was generated by AlecrimCoreData code generator tool.
//
//  Changes to this file may cause incorrect behavior and will be lost if
//  the code is regenerated.
//

import Foundation
import CoreData

import AlecrimCoreData

// MARK: - TFRecipient properties

extension TFRecipient {

    @NSManaged public var address: NSString?
    @NSManaged public var identifier: NSString?
    @NSManaged public var name: NSString?

    @NSManaged public var transactions: NSSet

}

// MARK: - TFRecipient KVC compliant to-many accessors and helpers

extension TFRecipient {

    @NSManaged private func addTransactionsObject(object: TFTransaction)
    @NSManaged private func removeTransactionsObject(object: TFTransaction)
    @NSManaged public func addTransactions(transactions: NSSet)
    @NSManaged public func removeTransactions(transactions: NSSet)

    public func addTransaction(transaction: TFTransaction) { self.addTransactionsObject(transaction) }
    public func removeTransaction(transaction: TFTransaction) { self.removeTransactionsObject(transaction) }

}

// MARK: - TFRecipient query attributes

extension TFRecipient {

    public static let address = AlecrimCoreData.NullableAttribute<NSString>("address")
    public static let identifier = AlecrimCoreData.NullableAttribute<NSString>("identifier")
    public static let name = AlecrimCoreData.NullableAttribute<NSString>("name")

    public static let transactions = AlecrimCoreData.Attribute<NSSet>("transactions")

}

// MARK: - AttributeType extensions

extension AlecrimCoreData.AttributeType where Self.ValueType: TFRecipient {

    public var address: AlecrimCoreData.NullableAttribute<NSString> { return AlecrimCoreData.NullableAttribute<NSString>("address", self) }
    public var identifier: AlecrimCoreData.NullableAttribute<NSString> { return AlecrimCoreData.NullableAttribute<NSString>("identifier", self) }
    public var name: AlecrimCoreData.NullableAttribute<NSString> { return AlecrimCoreData.NullableAttribute<NSString>("name", self) }

    public var transactions: AlecrimCoreData.Attribute<NSSet> { return AlecrimCoreData.Attribute<NSSet>("transactions", self) }

}

// MARK: - DataContext extensions

extension DataContext {

    public var tfrecipients: AlecrimCoreData.Table<TFRecipient> { return AlecrimCoreData.Table<TFRecipient>(dataContext: self) }

}

