//
//  TFTransaction.generated.swift
//
//  This code was generated by AlecrimCoreData code generator tool.
//
//  Changes to this file may cause incorrect behavior and will be lost if
//  the code is regenerated.
//

import Foundation
import CoreData

import AlecrimCoreData

// MARK: - TFTransaction properties

extension TFTransaction {

    @NSManaged var amount: NSNumber?
    @NSManaged var comment: NSString?
    @NSManaged var date: NSDate?
    @NSManaged var descriptionText: NSString?
    @NSManaged var identifier: NSString?
    @NSManaged var transactionType: NSString?

    @NSManaged var card: TFCard?
    @NSManaged var category: TFCategory?
    @NSManaged var currency: TFCurrency?
    @NSManaged var recipient: TFRecipient?

}

// MARK: - TFTransaction query attributes

extension TFTransaction {

    static let amount = AlecrimCoreData.NullableAttribute<NSNumber>("amount")
    static let comment = AlecrimCoreData.NullableAttribute<NSString>("comment")
    static let date = AlecrimCoreData.NullableAttribute<NSDate>("date")
    static let descriptionText = AlecrimCoreData.NullableAttribute<NSString>("descriptionText")
    static let identifier = AlecrimCoreData.NullableAttribute<NSString>("identifier")
    static let transactionType = AlecrimCoreData.NullableAttribute<NSString>("transactionType")

    static let card = AlecrimCoreData.NullableAttribute<TFCard>("card")
    static let category = AlecrimCoreData.NullableAttribute<TFCategory>("category")
    static let currency = AlecrimCoreData.NullableAttribute<TFCurrency>("currency")
    static let recipient = AlecrimCoreData.NullableAttribute<TFRecipient>("recipient")

}

// MARK: - AttributeType extensions

extension AlecrimCoreData.AttributeType where Self.ValueType: TFTransaction {

    var amount: AlecrimCoreData.NullableAttribute<NSNumber> { return AlecrimCoreData.NullableAttribute<NSNumber>("amount", self) }
    var comment: AlecrimCoreData.NullableAttribute<NSString> { return AlecrimCoreData.NullableAttribute<NSString>("comment", self) }
    var date: AlecrimCoreData.NullableAttribute<NSDate> { return AlecrimCoreData.NullableAttribute<NSDate>("date", self) }
    var descriptionText: AlecrimCoreData.NullableAttribute<NSString> { return AlecrimCoreData.NullableAttribute<NSString>("descriptionText", self) }
    var identifier: AlecrimCoreData.NullableAttribute<NSString> { return AlecrimCoreData.NullableAttribute<NSString>("identifier", self) }
    var transactionType: AlecrimCoreData.NullableAttribute<NSString> { return AlecrimCoreData.NullableAttribute<NSString>("transactionType", self) }

    var card: AlecrimCoreData.NullableAttribute<TFCard> { return AlecrimCoreData.NullableAttribute<TFCard>("card", self) }
    var category: AlecrimCoreData.NullableAttribute<TFCategory> { return AlecrimCoreData.NullableAttribute<TFCategory>("category", self) }
    var currency: AlecrimCoreData.NullableAttribute<TFCurrency> { return AlecrimCoreData.NullableAttribute<TFCurrency>("currency", self) }
    var recipient: AlecrimCoreData.NullableAttribute<TFRecipient> { return AlecrimCoreData.NullableAttribute<TFRecipient>("recipient", self) }

}

// MARK: - DataContext extensions

extension DataContext {

    var tftransactions: AlecrimCoreData.Table<TFTransaction> { return AlecrimCoreData.Table<TFTransaction>(dataContext: self) }

}

