//
//  TFTransaction.generated.swift
//
//  This code was generated by AlecrimCoreData code generator tool.
//
//  Changes to this file may cause incorrect behavior and will be lost if
//  the code is regenerated.
//

import Foundation
import CoreData

import AlecrimCoreData

// MARK: - TFTransaction properties

extension TFTransaction {

    @NSManaged public var amount: NSNumber?
    @NSManaged public var comment: NSString?
    @NSManaged public var date: NSDate?
    @NSManaged public var descriptionText: NSString?
    @NSManaged public var identifier: NSString?

    @NSManaged public var card: TFCard?
    @NSManaged public var category: TFCategory?
    @NSManaged public var currency: TFCurrency?
    @NSManaged public var recipient: TFRecipient?

}

// MARK: - TFTransaction query attributes

extension TFTransaction {

    public static let amount = AlecrimCoreData.NullableAttribute<NSNumber>("amount")
    public static let comment = AlecrimCoreData.NullableAttribute<NSString>("comment")
    public static let date = AlecrimCoreData.NullableAttribute<NSDate>("date")
    public static let descriptionText = AlecrimCoreData.NullableAttribute<NSString>("descriptionText")
    public static let identifier = AlecrimCoreData.NullableAttribute<NSString>("identifier")

    public static let card = AlecrimCoreData.NullableAttribute<TFCard>("card")
    public static let category = AlecrimCoreData.NullableAttribute<TFCategory>("category")
    public static let currency = AlecrimCoreData.NullableAttribute<TFCurrency>("currency")
    public static let recipient = AlecrimCoreData.NullableAttribute<TFRecipient>("recipient")

}

// MARK: - AttributeType extensions

extension AlecrimCoreData.AttributeType where Self.ValueType: TFTransaction {

    public var amount: AlecrimCoreData.NullableAttribute<NSNumber> { return AlecrimCoreData.NullableAttribute<NSNumber>("amount", self) }
    public var comment: AlecrimCoreData.NullableAttribute<NSString> { return AlecrimCoreData.NullableAttribute<NSString>("comment", self) }
    public var date: AlecrimCoreData.NullableAttribute<NSDate> { return AlecrimCoreData.NullableAttribute<NSDate>("date", self) }
    public var descriptionText: AlecrimCoreData.NullableAttribute<NSString> { return AlecrimCoreData.NullableAttribute<NSString>("descriptionText", self) }
    public var identifier: AlecrimCoreData.NullableAttribute<NSString> { return AlecrimCoreData.NullableAttribute<NSString>("identifier", self) }

    public var card: AlecrimCoreData.NullableAttribute<TFCard> { return AlecrimCoreData.NullableAttribute<TFCard>("card", self) }
    public var category: AlecrimCoreData.NullableAttribute<TFCategory> { return AlecrimCoreData.NullableAttribute<TFCategory>("category", self) }
    public var currency: AlecrimCoreData.NullableAttribute<TFCurrency> { return AlecrimCoreData.NullableAttribute<TFCurrency>("currency", self) }
    public var recipient: AlecrimCoreData.NullableAttribute<TFRecipient> { return AlecrimCoreData.NullableAttribute<TFRecipient>("recipient", self) }

}

// MARK: - DataContext extensions

extension DataContext {

    public var tftransactions: AlecrimCoreData.Table<TFTransaction> { return AlecrimCoreData.Table<TFTransaction>(dataContext: self) }

}

